"""This package is for compatibility with v0.1.8 and below,v0.3.0 and above will be removed. """
from fastapi_amis_admin.admin.admin import (
    AdminApp,
    BaseAdmin,
    BaseAdminSite,
    BaseFormAdmin,
    BaseModelAction,
    BaseModelAdmin,
    FormAdmin,
    IframeAdmin,
    LinkAdmin,
    LinkModelForm,
    ModelAction,
    ModelAdmin,
    ModelFormAdmin,
    PageAdmin,
    PageSchemaAdmin,
    RouterAdmin,
    TemplateAdmin,
)
